language: java
jdk:
  - oraclejdk8
sudo: required
dist: trusty
before_script:
  - npm install -g bower
  - cd influunt-app && npm install && bower install && cd ..
  - curl https://www.jpm4j.org/install/script | sudo sh
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
  - wget http://downloads.typesafe.com/typesafe-activator/1.3.10/typesafe-activator-1.3.10-minimal.zip
  - unzip -q typesafe-activator-1.3.10-minimal.zip
script: cd influunt-app && npm test && cd ../influunt-api && ../activator-1.3.10-minimal/bin/activator jacoco:cover
after_script:
  - codacy-coverage-reporter -l Java -r target/scala-2.11/jacoco/jacoco.xml
  - cat ../influunt-app/coverage/lcov.info | ../influunt-app/node_modules/.bin/codacy-coverage
notifications:
  slack: influunt:dcSLFuPoNSbWFijZ4jOJFVeE
