site_name: Influunt Documentação
theme: readthedocs
pages:
- Home: 'index.md'
- Comunicação:
    - 'Introdução': 'comunicacao/introducao.md'
    - 'Envelope': 'comunicacao/envelope.md'
    - 'Segurança': 'comunicacao/seguranca.md'
- Protocolos:
  - Alto Nível:
    - 'Introdução': 'protocolos/alto_nivel/introducao.md'
    - 'Conectividade': 'protocolos/alto_nivel/conectividade.md'
    - 'Ciclo de Vida': 'protocolos/alto_nivel/ciclo_vida.md'
    - 'Configuração do Controlador': 'protocolos/alto_nivel/configuracao.md'
    - 'Transações': 'protocolos/alto_nivel/transacoes.md'
    - 'Alertas e Falhas': 'protocolos/alto_nivel/alertas_e_falhas.md'
  - Baixo Nível:
    - 'Introdução': 'protocolos/baixo_nivel/introducao.md'

